global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prediction_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prediction_service:9090']

# scrape_configs:
#   - job_name: 'evidently'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['evidently:8085']
#   - job_name: 'python_service'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['realdatasim:8000']
