#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - apt-transport-https
  - lsb-release
  - gnupg
  - wget
runcmd:
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-get update -y
  - sudo apt install make
  - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io -y
  - sudo usermod -aG docker ${USER}
  - newgrp docker
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - sudo apt-get install azure-cli gnome-keyring -y
  - wget https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
  - bash Anaconda3-2024.02-1-Linux-x86_64.sh -b -p /opt/anaconda3
  - echo 'export PATH=/opt/anaconda3/bin:$PATH' >> /home/azureuser/.bashrc
  - az login --identity --allow-no-subscriptions
  - connection_string=$(az keyvault secret show --name storage-connection-string --vault-name mlopsproject-kv --query value -o tsv)
  - echo 'export AZURE_STORAGE_CONNECTION_STRING='\'$connection_string\' >> /home/azureuser/.bashrc
  - source /home/azureuser/.bashrc
  - git clone https://github.com/caiomiyashiro/mlops_zoomcamp_finalproject.git /home/azureuser/mlops_zoomcamp_finalproject
  - cd /home/azureuser/mlops_zoomcamp_finalproject
  - cp .env.sample .env
  - make docker-up
