#cloud-config
runcmd:
  - sudo apt-get update -y
  - sudo apt-get install docker.io -y
  - sudo apt-get install docker-compose -y
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - wget https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh
  - bash Anaconda3-2024.02-1-Linux-x86_64.sh -b
  - echo 'export PATH=\"/home/azureuser/anaconda3/bin:$PATH\"' >> ~/.bashrc
  - source ~/.bashrc
